"""Orchestrator + Reviewer — both run on Databricks via OpenAI SDK.

V2 dynamic skills model:
- Per-task Skill.md generated fresh by orchestrator (meta-thinking)
- Stored at <workspace>/skills/Skill.md
- Global skill at chief-of-staff/skills/global.md grows via auto-promotion
- No keyword-based domain detection. The orchestrator decides what each task needs.

The HUMAN USER is the Supervisor. The LLMs serve them:
  Orchestrator (manager): meta-thinks Skill.md, asks Qs, builds brief, builds corrections,
                          finds promotable lessons after task completion.
  Reviewer (independent QA):  per-action review, final review.
                              Sees only goal + action stream + Skill.md (the public plan).
"""
import json
import re
from pathlib import Path

from openai import OpenAI

from config import (
    DATABRICKS_BASE_URL,
    DATABRICKS_MODEL,
    DATABRICKS_TOKEN,
    PROJECT_ROOT,
    PROMPTS_DIR,
)

SKILLS_DIR = PROJECT_ROOT / "skills"
GLOBAL_SKILL_PATH = SKILLS_DIR / "global.md"
LEARNED_HEADER = "## Learned from past runs"
MAX_LEARNED_ENTRIES = 50


def _client() -> OpenAI:
    return OpenAI(
        api_key=DATABRICKS_TOKEN,
        base_url=DATABRICKS_BASE_URL,
        max_retries=5,
        timeout=120.0,
    )


def _load_prompt(name: str) -> str:
    return (PROMPTS_DIR / f"{name}.md").read_text()


def _load_skills(workspace: str | Path | None = None) -> str:
    """Load global skill + per-task SKILL.md (if workspace path given)."""
    parts: list[str] = []
    if GLOBAL_SKILL_PATH.exists():
        parts.append(f"## Global skills (universal patterns)\n\n{GLOBAL_SKILL_PATH.read_text()}")
    if workspace:
        ws = Path(workspace) / "skills"
        for fname in ("SKILL.md", "Skill.md"):
            p = ws / fname
            if p.exists():
                parts.append(f"## Skill brief for THIS task (generated by you)\n\n{p.read_text()}")
                break
    return "\n\n---\n\n".join(parts)


def _chat(system: str, user: str, max_tokens: int = 2048, skills_context: str = "") -> str:
    full_system = system
    if skills_context:
        full_system = (
            f"{system}\n\n"
            "## Available skills / knowledge for this task\n"
            "Treat these as authoritative knowledge supplementing your judgment.\n\n"
            f"{skills_context}"
        )

    last_err: Exception | None = None
    for attempt in range(3):
        try:
            response = _client().chat.completions.create(
                model=DATABRICKS_MODEL,
                max_tokens=max_tokens,
                messages=[
                    {"role": "system", "content": full_system},
                    {"role": "user", "content": user},
                ],
            )
            return response.choices[0].message.content or ""
        except Exception as e:
            last_err = e
            err_str = str(e).lower()
            transient = any(s in err_str for s in (
                "rate limit", "rate_limit", "429",
                "503", "502", "504", "timeout", "timed out",
                "connection", "temporary", "overloaded",
            ))
            if not transient or attempt == 2:
                raise
            wait = 2 ** (attempt + 1)
            print(f"[orchestrator] transient Databricks error (attempt {attempt+1}): {e}. retrying in {wait}s")
            import time as _time
            _time.sleep(wait)
    if last_err:
        raise last_err
    return ""


def _extract_json(text: str) -> dict:
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        return {}
    try:
        return json.loads(match.group(0))
    except json.JSONDecodeError:
        return {}


def append_to_global(lessons: list[str]) -> int:
    """Append lessons to skills/global.md under the Learned section. Dedupes. Caps at MAX_LEARNED_ENTRIES."""
    if not lessons:
        return 0
    SKILLS_DIR.mkdir(parents=True, exist_ok=True)
    existing = GLOBAL_SKILL_PATH.read_text() if GLOBAL_SKILL_PATH.exists() else "# Global skills\n\n"

    if LEARNED_HEADER not in existing:
        existing = existing.rstrip() + f"\n\n{LEARNED_HEADER}\n\n"

    head, _, tail = existing.partition(LEARNED_HEADER)
    learned_section = (LEARNED_HEADER + tail).strip()
    lines = [l for l in learned_section.splitlines() if l.startswith("- ")]
    seen = set(lines)
    added = 0
    for l in lessons:
        clean = l.strip().lstrip("-").strip()
        if not clean:
            continue
        new_line = f"- {clean}"
        if new_line in seen:
            continue
        lines.append(new_line)
        seen.add(new_line)
        added += 1
    if len(lines) > MAX_LEARNED_ENTRIES:
        lines = lines[-MAX_LEARNED_ENTRIES:]

    rebuilt = head.rstrip() + "\n\n" + LEARNED_HEADER + "\n\n" + "\n".join(lines) + "\n"
    GLOBAL_SKILL_PATH.write_text(rebuilt)
    return added


def save_task_skill(workspace: str | Path, skill_md: str) -> Path:
    """Write the per-task SKILL.md (Anthropic skill-creator pattern) to <workspace>/skills/SKILL.md."""
    skills_dir = Path(workspace) / "skills"
    skills_dir.mkdir(parents=True, exist_ok=True)
    p = skills_dir / "SKILL.md"
    p.write_text(skill_md)
    return p


class Orchestrator:
    """Manager role — meta-thinking, questions, brief, correction prompts, auto-resolve."""

    def __init__(self):
        self.system = _load_prompt("orchestrator")

    def think_and_ask(self, task: str) -> dict:
        """Phase 1 — meta-think + ask clarifying questions in one LLM call.
        The orchestrator first thinks about what the task NEEDS, then asks sharper Qs.
        Returns {'skill_preview': str, 'questions': [str]}.
        """
        skills = _load_skills()
        user = (
            "Phase 1 — meta-think + clarify.\n\n"
            f"User's task:\n{task}\n\n"
            "Step A: think about what this task actually requires. Identify:\n"
            "  - the kind of work (code build, research, writing, data, ops, etc.)\n"
            "  - the likely 'done' criteria\n"
            "  - failure patterns specific to THIS kind of task\n"
            "  - what verification will prove the goal was met\n"
            "  - gotchas and edge cases\n\n"
            "Step B: propose 3-5 clarifying questions that GROUND the LLM's understanding of the user's intent. "
            "Even when you think you can decide an answer yourself, ask anyway — questions force the user to commit to specifics, "
            "which reduces hallucination and drift during execution. Aim for 3-5 questions, not 1-2.\n\n"
            "Output JSON exactly:\n"
            '{"skill_preview": "<concise markdown summary of your meta-thinking — what this task needs>", '
            '"questions": ["...", "..."]}\n'
            "Keep skill_preview under 1200 chars. Questions: 0-5 items, fewer is better."
        )
        raw = _chat(self.system, user, max_tokens=2048, skills_context=skills)
        data = _extract_json(raw)
        return {
            "skill_preview": (data.get("skill_preview") or "").strip(),
            "questions": (data.get("questions") or [])[:5],
        }

    def generate_skill_brief(
        self,
        task: str,
        clarifications: dict[str, str],
        skill_preview: str = "",
    ) -> str:
        """Phase 2 — produce the final SKILL.md given task + answers.
        Follows Anthropic's skill-creator format: YAML frontmatter + body.

        If skill_preview (from think_and_ask) is provided, refine it instead of regenerating —
        saves an LLM round of meta-thinking.
        """
        skills = _load_skills()
        clarif_text = "\n".join(f"- Q: {q}\n  A: {a}" for q, a in clarifications.items()) or "(none)"
        if skill_preview:
            user = (
                "Phase 2 — refine your earlier meta-thinking into the final SKILL.md.\n\n"
                f"Task: {task}\n\n"
                f"Your earlier preview (from question-asking phase):\n{skill_preview}\n\n"
                f"Clarifications you got from the user:\n{clarif_text}\n\n"
                "REFINE the preview into a final SKILL.md, incorporating what the clarifications tell you. "
                "Don't restart from zero — reuse the structure and insights from the preview, sharpen them with the answers.\n\n"
                "Output the SKILL.md exactly in this format:\n\n"
                "```\n"
                "---\n"
                "name: <short-kebab-case-id-derived-from-task>\n"
                "description: <one sentence saying when to apply this skill — be 'pushy' (Anthropic skill-creator convention) so it triggers reliably on similar future tasks>\n"
                "---\n\n"
                "# <Title>\n\n"
                "## Objective\n<concrete goal for THIS task>\n\n"
                "## What 'done' means\n<verifiable end state>\n\n"
                "## Knowledge / standards that apply\n<only what's relevant>\n\n"
                "## Failure patterns to watch for\n<specific to this kind of work>\n\n"
                "## Verification required\n<what proof you'll demand>\n\n"
                "## Gotchas\n<common mistakes>\n\n"
                "## Scope boundaries\n<in / out>\n"
                "```\n\n"
                "Output only the SKILL.md content (frontmatter + body). No preamble, no code fences around the whole thing."
            )
        else:
            user = (
                "Phase 2 — generate the SKILL.md for this task (Anthropic skill-creator format).\n\n"
                f"Task: {task}\n\n"
                f"Clarifications:\n{clarif_text}\n\n"
                "Output the SKILL.md exactly in this format:\n\n"
                "```\n"
                "---\n"
                "name: <short-kebab-case-id-derived-from-task>\n"
                "description: <one sentence saying when to apply this skill — be 'pushy' so it triggers reliably on similar future tasks>\n"
                "---\n\n"
                "# <Title>\n\n"
                "## Objective\n## What 'done' means\n## Knowledge / standards that apply\n"
                "## Failure patterns to watch for\n## Verification required\n## Gotchas\n## Scope boundaries\n"
                "```\n\n"
                "Be specific to THIS task. Output only the SKILL.md content. No preamble."
            )
        return _chat(self.system, user, max_tokens=3500, skills_context=skills).strip()

    def build_brief(self, task: str, clarifications: dict[str, str], workspace: str) -> str:
        """Build the executor brief. The brief is what gets passed to Claude Code as the prompt."""
        skills = _load_skills(workspace=workspace)
        clarif_text = "\n".join(f"- Q: {q}\n  A: {a}" for q, a in clarifications.items()) or "(none)"
        user = (
            "Phase 3 — build the executor brief.\n\n"
            f"Task: {task}\n\n"
            f"Clarifications:\n{clarif_text}\n\n"
            "Write a precise brief that an executor (Claude Code) can run with no further questions. "
            "Use the Skill brief above as your authoritative guide. Structure:\n"
            "- Objective\n"
            "- What needs to be built / produced\n"
            "- Done / acceptance criteria (numbered, verifiable)\n"
            "- Constraints\n"
            "- Quality bar\n"
            "- Recommended implementation shape (only if useful)\n\n"
            "Output markdown only, no preamble."
        )
        return _chat(self.system, user, max_tokens=4096, skills_context=skills).strip()

    def build_correction_prompt(self, brief: str, supervisor_issues: list[str]) -> str:
        issues_text = "\n".join(f"- {i}" for i in supervisor_issues) or "- (no specific issues recorded)"
        return (
            "Continue working on the original task. The independent reviewer found issues "
            "in your previous attempt that must be fixed before the work can be marked done.\n\n"
            f"Original brief:\n{brief}\n\n"
            f"Issues to fix:\n{issues_text}\n\n"
            "Address every issue. After fixing, run the verification step (build / test / "
            "whatever proves the goal was met) and show its output."
        )

    def auto_resolve_escalation(
        self,
        goal: str,
        brief: str,
        action_log_summary: str,
        question: str,
        option_a: str,
        option_b: str,
        workspace: str | None = None,
    ) -> str:
        skills = _load_skills(workspace=workspace)
        user = (
            "An escalation timed out (user did not respond within 30 minutes). "
            "Make the best judgment for the user given the full context. "
            "Pick option A or option B based on which serves the goal better.\n\n"
            f"Goal: {goal}\n\n"
            f"Brief: {brief}\n\n"
            f"What has happened so far:\n{action_log_summary}\n\n"
            f"Escalation question: {question}\n"
            f"A) {option_a}\n"
            f"B) {option_b}\n\n"
            'Respond with JSON only: {"choice": "a" or "b", "rationale": "one sentence"}'
        )
        raw = _chat(self.system, user, max_tokens=512, skills_context=skills)
        data = _extract_json(raw)
        choice = (data.get("choice") or "a").lower()
        return choice if choice in ("a", "b") else "a"

    def find_promotable_lessons(
        self,
        task: str,
        skill_md: str,
        brief: str,
        action_log_summary: str,
        review_summary: str,
        review_issues: list[str],
        passed: bool,
        workspace: str | None = None,
    ) -> list[str]:
        """After a task, identify lessons GENERAL enough to apply to future different tasks.
        Filter aggressively. Return list of 0-3 actionable sentences."""
        skills = _load_skills(workspace=workspace)
        outcome = "PASSED" if passed else "FAILED"
        issues_text = "\n".join(f"- {i}" for i in review_issues[:5]) or "- (none)"
        user = (
            "Phase 4 — promote lessons.\n\n"
            "A task just completed. Identify lessons GENERAL enough to apply to future DIFFERENT tasks. "
            "Filter aggressively — most things are too specific. We promote only if a future "
            "task in a different domain would benefit. Avoid restating things already in the global skills above.\n\n"
            f"Task: {task}\n"
            f"Outcome: {outcome}\n"
            f"Skill brief that guided this task:\n{skill_md[:2000]}\n\n"
            f"Brief excerpt:\n{brief[:1000]}\n\n"
            f"Action log summary:\n{action_log_summary[:2000]}\n\n"
            f"Review summary: {review_summary}\n"
            f"Issues caught:\n{issues_text}\n\n"
            "Output JSON: {\"lessons\": [\"...\", \"...\"]}.\n"
            "Each lesson:\n"
            "  - One sentence\n"
            "  - Actionable for a future reviewer/orchestrator\n"
            "  - General — applies to a DIFFERENT task, not just a similar one\n"
            "  - NOT already in the global skills above\n"
            "Empty list is the right answer most of the time."
        )
        raw = _chat(self.system, user, max_tokens=1024, skills_context=skills)
        data = _extract_json(raw)
        lessons = data.get("lessons") or []
        return [l.strip() for l in lessons if isinstance(l, str) and l.strip()][:3]


class Reviewer:
    """Independent QA reviewer — sees only goal + action log + Skill.md. Blind to the brief."""

    def __init__(self):
        self.system = _load_prompt("reviewer")

    def review_action(
        self,
        goal: str,
        tool_name: str,
        tool_input: dict,
        tool_output: str | None = None,
        recent_actions: str = "",
        workspace: str | None = None,
    ) -> dict:
        skills = _load_skills(workspace=workspace)
        user = (
            f"Goal: {goal}\n\n"
            f"Recent actions:\n{recent_actions}\n\n"
            f"Action under review:\n"
            f"  Tool: {tool_name}\n"
            f"  Input: {json.dumps(tool_input)[:500]}\n"
            f"  Output: {(tool_output or '')[:500]}\n\n"
            "Phase: per-action review. Output JSON only."
        )
        raw = _chat(self.system, user, max_tokens=512, skills_context=skills)
        data = _extract_json(raw)
        return {
            "decision": data.get("decision", "approve"),
            "message": data.get("message", ""),
        }

    def final_review(self, goal: str, action_log: str, workspace: str | None = None) -> dict:
        skills = _load_skills(workspace=workspace)
        user = (
            f"Goal: {goal}\n\n"
            f"Full action log:\n{action_log}\n\n"
            "Phase: final review. Output JSON only.\n"
            "Set passed=true ONLY if BOTH conditions hold:\n"
            "  (a) there is demonstrable verification evidence in the log, AND\n"
            "  (b) you have NO issues to list.\n"
            "If you list ANY issues, you MUST set passed=false. Issues are blockers, not warnings."
        )
        raw = _chat(self.system, user, max_tokens=2048, skills_context=skills)
        data = _extract_json(raw)
        issues = data.get("issues", []) or []
        passed = bool(data.get("passed", False))
        if issues:
            passed = False
        return {
            "passed": passed,
            "issues": issues,
            "summary": data.get("summary", ""),
        }
